# Site settings
title: CofresiLab
subtitle: Addiction Neuroscience
email: cofresilab@gmail.com
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:
street_address: 115 Melvin H. Marx Building, 1416 Carrie Francke Drive
city: Columbia
state: MO
zip_code: 65211-3470
country: United States of America
phone: 

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/rcofresi
gitlab_url: 
googleplus_url:
instagram_url: 
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/cofresi_lab
google_scholar_url: https://scholar.google.com/citations?user=nRAErPEAAAAJ&hl=en

# Build settings
markdown: kramdown
highlighter: rouge

